//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradesWebApplication.DAL.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measure_Type
    {
        public Measure_Type()
        {
            this.Trade_Performance = new HashSet<Trade_Performance>();
        }
    
        public int measure_type_id { get; set; }
        public string measure_type_label { get; set; }
    
        public virtual ICollection<Trade_Performance> Trade_Performance { get; set; }
    }
}
