//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradesWebApplication.Data.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BCATradeEntitiesConnection : DbContext
    {
        public BCATradeEntitiesConnection()
            : base("name=BCATradeEntitiesConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Benchmark> Benchmarks { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Hedge_Type> Hedge_Type { get; set; }
        public virtual DbSet<Instruction_Type> Instruction_Type { get; set; }
        public virtual DbSet<Length_Type> Length_Type { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Measure_Type> Measure_Type { get; set; }
        public virtual DbSet<MSpeer_lsns> MSpeer_lsns { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Related_Trade> Related_Trade { get; set; }
        public virtual DbSet<Relativity> Relativities { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Structure_Type> Structure_Type { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<sysreplserver> sysreplservers { get; set; }
        public virtual DbSet<Track_Record> Track_Record { get; set; }
        public virtual DbSet<Track_Record_Type> Track_Record_Type { get; set; }
        public virtual DbSet<Tradable_Thing> Tradable_Thing { get; set; }
        public virtual DbSet<Tradable_Thing_Class> Tradable_Thing_Class { get; set; }
        public virtual DbSet<Trade> Trades { get; set; }
        public virtual DbSet<Trade_Comment> Trade_Comment { get; set; }
        public virtual DbSet<Trade_Instruction> Trade_Instruction { get; set; }
        public virtual DbSet<Trade_Line> Trade_Line { get; set; }
        public virtual DbSet<Trade_Line_Group> Trade_Line_Group { get; set; }
        public virtual DbSet<Trade_Line_Group_Type> Trade_Line_Group_Type { get; set; }
        public virtual DbSet<Trade_Performance> Trade_Performance { get; set; }
        public virtual DbSet<MSpeer_request> MSpeer_request { get; set; }
        public virtual DbSet<MSpeer_response> MSpeer_response { get; set; }
        public virtual DbSet<MSpub_identity_range> MSpub_identity_range { get; set; }
        public virtual DbSet<sysarticlecolumn> sysarticlecolumns { get; set; }
        public virtual DbSet<sysarticle> sysarticles { get; set; }
        public virtual DbSet<sysarticleupdate> sysarticleupdates { get; set; }
        public virtual DbSet<syspublication> syspublications { get; set; }
        public virtual DbSet<sysschemaarticle> sysschemaarticles { get; set; }
        public virtual DbSet<syssubscription> syssubscriptions { get; set; }
        public virtual DbSet<systranschema> systranschemas { get; set; }
    }
}
